image:
  repo: ghcr.io/digital-asset/splice-portfolio/docker
  tag: ""

# @schema additionalProperties: true
nodeSelector: {}

# @schema additionalProperties: true
affinity: {}

tolerations: []

config:
  amulet:
    validatorUrl: "http://localhost:2000/api/validator" # @schema required
    registry: "http://scan.localhost:4000/registry/" # @schema required
  token:
    validatorUrl: "http://localhost:2000/api/validator" # @schema required
    registries:
      - url: "https://registry.example.com" # @schema required
        name: "" # (optional)
        partyId: "party-hint::fingerprint" # (optional)
