{{- $confHash := .Values.config | toPrettyJson | sha256sum | trunc 6 -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-wallet-gateway-config-{{ $confHash }}"
  namespace: "{{ .Release.Namespace }}"
data:
  config.json: |
    {{- .Values.config | toPrettyJson | nindent 4 }}
