server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location = /config.json {
        try_files /config.json =404;
        add_header Cache-Control "no-store";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

